#!/bin/bash

server=$1
project=$2
deployment=$3

buildDir=/tmp/sve-$project-$deployment

serverRoot=apps/$project/$deployment

function run {
	echo $1
	$1
}

run "ssh $server rm -rf $serverRoot/artifacts"
run "ssh $server mkdir -p $serverRoot/artifacts"
run "scp -r $buildDir $server:$serverRoot/artifacts/pages"
run "scp -r artifacts/css $server:$serverRoot/artifacts/css"
